[package]
name = "osi-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
rand = "0.8.5"
rand-sequence = "0.1.1"
nom = "7.1.3"
smallvec = "1.11.1"
