[package]
name = "x690"
version = "1.2.0"
edition = "2024"
authors = [
    "Jonathan M. Wilbur <jonathan@wilbur.space>",
    "Wildboar Software <jonathan.wilbur@wildboarsoftware.com>",
]
description = "Basic Encoding Rules (BER) and Distinguished Encoding Rules (DER) as specified in ITU-T Recommendation X.690"
readme = "README.md"
repository = "https://github.com/JonathanWilbur/asn1.rs/tree/master/x690"
license = "MIT"
keywords = ["basic", "distinguished", "encoding", "ber", "der"]
categories = ["encoding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wildboar-asn1 = { path = "../asn1", version = "3" }
iso6093 = { path = "../iso6093", version = "1" }
bytes = "1.4.0"
simdutf8 = { version = "0.1.4", optional = true }
likely_stable = { version = "0.1.3", optional = true }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "decode"
harness = false

[features]
default = ["der"]
der = []
