[package]
name = "x690"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1 = { path = "../asn1" }
bitvec = "1"
chrono = "0.4.19"
num = "0.4.0"
