[package]
name = "x690"
version = "0.1.0"
edition = "2021"
authors = [
    "Jonathan M. Wilbur <jonathan@wilbur.space>",
    "Wildboar Software <jonathan.wilbur@wildboarsoftware.com>",
]
description = "Basic Encoding Rules (BER) and Distinguished Encoding Rules (DER)"
readme = "README.md"
repository = "https://github.com/JonathanWilbur/asn1.rs/tree/master/x690"
license = "MIT"
keywords = ["basic", "distinguished", "encoding", "ber", "der"]
categories = ["encoding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1 = { path = "../asn1" }
smallvec = "1.11.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "decode"
harness = false
