pub fn x121_dcc_country_code_to_iso_3166 (dcc: u16) -> Option<[u8; 2]> {
    match dcc {
        202 => Some([b'G', b'R']), // Greece
        204 => Some([b'N', b'L']), // Netherlands (Kingdom of the)
        205 => Some([b'N', b'L']), // Netherlands (Kingdom of the)
        206 => Some([b'B', b'E']), // Belgium
        208 => Some([b'F', b'R']), // France
        209 => Some([b'F', b'R']), // France
        210 => Some([b'F', b'R']), // France
        211 => Some([b'F', b'R']), // France
        212 => Some([b'M', b'C']), // Monaco (Principality of)
        213 => Some([b'A', b'D']), // Andorra (Principality of)
        214 => Some([b'E', b'S']), // Spain
        215 => Some([b'E', b'S']), // Spain
        216 => Some([b'H', b'U']), // Hungary (Republic of)
        218 => Some([b'B', b'A']), // Bosnia and Herzegovina
        219 => Some([b'H', b'R']), // Croatia (Republic of)
        220 => Some([b'Y', b'U']), // Yugoslavia (Federal Republic of) [Note: "YU" is outdated since Yugoslavia dissolved; you might want to use "RS" for Serbia or another relevant code]
        222 => Some([b'I', b'T']), // Italy
        223 => Some([b'I', b'T']), // Italy
        224 => Some([b'I', b'T']), // Italy
        225 => Some([b'V', b'A']), // Vatican City State
        226 => Some([b'R', b'O']), // Romania
        228 => Some([b'C', b'H']), // Switzerland (Confederation of)
        229 => Some([b'C', b'H']), // Switzerland (Confederation of)
        230 => Some([b'C', b'Z']), // Czech Republic
        231 => Some([b'S', b'K']), // Slovak Republic
        232 => Some([b'A', b'T']), // Austria
        233 => Some([b'A', b'T']), // Austria
        234 => Some([b'G', b'B']), // United Kingdom of Great Britain and Northern Ireland
        235 => Some([b'G', b'B']), // United Kingdom of Great Britain and Northern Ireland
        236 => Some([b'G', b'B']), // United Kingdom of Great Britain and Northern Ireland
        237 => Some([b'G', b'B']), // United Kingdom of Great Britain and Northern Ireland
        238 => Some([b'D', b'K']), // Denmark
        239 => Some([b'D', b'K']), // Denmark
        240 => Some([b'S', b'E']), // Sweden
        242 => Some([b'N', b'O']), // Norway
        243 => Some([b'N', b'O']), // Norway
        244 => Some([b'F', b'I']), // Finland
        246 => Some([b'L', b'T']), // Lithuania (Republic of)
        247 => Some([b'L', b'V']), // Latvia (Republic of)
        248 => Some([b'E', b'E']), // Estonia (Republic of)
        250 => Some([b'R', b'U']), // Russian Federation
        251 => Some([b'R', b'U']), // Russian Federation
        255 => Some([b'U', b'A']), // Ukraine
        257 => Some([b'B', b'Y']), // Belarus (Republic of)
        259 => Some([b'M', b'D']), // Moldova (Republic of)
        260 => Some([b'P', b'L']), // Poland (Republic of)
        261 => Some([b'P', b'L']), // Poland (Republic of)
        262 => Some([b'D', b'E']), // Germany (Federal Republic of)
        263 => Some([b'D', b'E']), // Germany (Federal Republic of)
        264 => Some([b'D', b'E']), // Germany (Federal Republic of)
        265 => Some([b'D', b'E']), // Germany (Federal Republic of)
        266 => Some([b'G', b'I']), // Gibraltar
        268 => Some([b'P', b'T']), // Portugal
        269 => Some([b'P', b'T']), // Portugal
        270 => Some([b'L', b'U']), // Luxembourg
        272 => Some([b'I', b'E']), // Ireland
        274 => Some([b'I', b'S']), // Iceland
        276 => Some([b'A', b'L']), // Albania (Republic of)
        278 => Some([b'M', b'T']), // Malta
        280 => Some([b'C', b'Y']), // Cyprus (Republic of)
        282 => Some([b'G', b'E']), // Georgia
        283 => Some([b'A', b'M']), // Armenia (Republic of)
        284 => Some([b'B', b'G']), // Bulgaria (Republic of)
        286 => Some([b'T', b'R']), // Turkey
        288 => Some([b'F', b'O']), // Faroe Islands
        290 => Some([b'G', b'L']), // Greenland
        292 => Some([b'S', b'M']), // San Marino (Republic of)
        293 => Some([b'S', b'I']), // Slovenia (Republic of)
        294 => Some([b'M', b'K']), // The Former Yugoslav Republic of Macedonia [Note: This is the old name. Now officially "North Macedonia"]
        295 => Some([b'L', b'I']), // Liechtenstein (Principality of)
        302 => Some([b'C', b'A']), // Canada
        303 => Some([b'C', b'A']), // Canada
        308 => Some([b'P', b'M']), // Saint Pierre and Miquelon (Collectivité territoriale de la République française)
        310 => Some([b'U', b'S']), // United States of America
        311 => Some([b'U', b'S']), // United States of America
        312 => Some([b'U', b'S']), // United States of America
        313 => Some([b'U', b'S']), // United States of America
        314 => Some([b'U', b'S']), // United States of America
        315 => Some([b'U', b'S']), // United States of America
        316 => Some([b'U', b'S']), // United States of America
        330 => Some([b'P', b'R']), // Puerto Rico
        332 => Some([b'V', b'I']), // United States Virgin Islands
        334 => Some([b'M', b'X']), // Mexico
        335 => Some([b'M', b'X']), // Mexico
        338 => Some([b'J', b'M']), // Jamaica
        340 => Some([b'G', b'P']), // Guadeloupe (This code represents Guadeloupe, separate code might be needed for Martinique)
        342 => Some([b'B', b'B']), // Barbados
        344 => Some([b'A', b'G']), // Antigua and Barbuda
        346 => Some([b'K', b'Y']), // Cayman Islands
        348 => Some([b'V', b'G']), // British Virgin Islands
        350 => Some([b'B', b'M']), // Bermuda
        352 => Some([b'G', b'D']), // Grenada
        354 => Some([b'M', b'S']), // Montserrat
        356 => Some([b'K', b'N']), // Saint Kitts and Nevis
        358 => Some([b'L', b'C']), // Saint Lucia
        360 => Some([b'V', b'C']), // Saint Vincent and the Grenadines
        362 => Some([b'A', b'N']), // Netherlands Antilles [Note: This code is deprecated since the dissolution of the Netherlands Antilles in 2010]
        363 => Some([b'A', b'W']), // Aruba
        364 => Some([b'B', b'S']), // Bahamas (Commonwealth of the)
        365 => Some([b'A', b'I']), // Anguilla
        366 => Some([b'D', b'M']), // Dominica (Commonwealth of)
        368 => Some([b'C', b'U']), // Cuba
        370 => Some([b'D', b'O']), // Dominican Republic
        372 => Some([b'H', b'T']), // Haiti (Republic of)
        374 => Some([b'T', b'T']), // Trinidad and Tobago
        376 => Some([b'T', b'C']), // Turks and Caicos Islands
        400 => Some([b'A', b'Z']), // Azerbaijani Republic
        401 => Some([b'K', b'Z']), // Kazakstan (Republic of)
        404 => Some([b'I', b'N']), // India (Republic of)
        410 => Some([b'P', b'K']), // Pakistan (Islamic Republic of)
        411 => Some([b'P', b'K']), // Pakistan (Islamic Republic of)
        412 => Some([b'A', b'F']), // Afghanistan (Islamic State of)
        413 => Some([b'L', b'K']), // Sri Lanka (Democratic Socialist Republic of)
        414 => Some([b'M', b'M']), // Myanmar (Union of) [Note: Historically referred to as Burma]
        415 => Some([b'L', b'B']), // Lebanon
        416 => Some([b'J', b'O']), // Jordan (Hashemite Kingdom of)
        417 => Some([b'S', b'Y']), // Syrian Arab Republic
        418 => Some([b'I', b'Q']), // Iraq (Republic of)
        419 => Some([b'K', b'W']), // Kuwait (State of)
        420 => Some([b'S', b'A']), // Saudi Arabia (Kingdom of)
        421 => Some([b'Y', b'E']), // Yemen (Republic of)
        422 => Some([b'O', b'M']), // Oman (Sultanate of)
        424 => Some([b'A', b'E']), // United Arab Emirates
        425 => Some([b'I', b'L']), // Israel (State of)
        426 => Some([b'B', b'H']), // Bahrain (State of)
        427 => Some([b'Q', b'A']), // Qatar (State of)
        428 => Some([b'M', b'N']), // Mongolia
        429 => Some([b'N', b'P']), // Nepal
        430 => Some([b'A', b'E']), // United Arab Emirates (Abu Dhabi)
        431 => Some([b'A', b'E']), // United Arab Emirates (Dubai)
        432 => Some([b'I', b'R']), // Iran (Islamic Republic of)
        434 => Some([b'U', b'Z']), // Uzbekistan (Republic of)
        436 => Some([b'T', b'J']), // Tajikistan (Republic of)
        437 => Some([b'K', b'G']), // Kyrgyz Republic
        438 => Some([b'T', b'M']), // Turkmenistan
        440 => Some([b'J', b'P']), // Japan
        441 => Some([b'J', b'P']), // Japan
        442 => Some([b'J', b'P']), // Japan
        443 => Some([b'J', b'P']), // Japan
        450 => Some([b'K', b'R']), // Korea (Republic of)
        452 => Some([b'V', b'N']), // Viet Nam (Socialist Republic of)
        453 => Some([b'H', b'K']), // Hongkong
        454 => Some([b'H', b'K']), // Hongkong
        455 => Some([b'M', b'O']), // Macau
        456 => Some([b'K', b'H']), // Cambodia (Kingdom of)
        457 => Some([b'L', b'A']), // Lao People’s Democratic Republic
        460 => Some([b'C', b'N']), // China (People’s Republic of)
        466 => Some([b'T', b'W']), // Taiwan, China
        467 => Some([b'K', b'P']), // Democratic People’s Republic of Korea
        470 => Some([b'B', b'D']), // Bangladesh (People’s Republic of)
        472 => Some([b'M', b'V']), // Maldives (Republic of)
        480 => Some([b'K', b'R']), // Korea (Republic of)
        481 => Some([b'K', b'R']), // Korea (Republic of)
        502 => Some([b'M', b'Y']), // Malaysia
        505 => Some([b'A', b'U']), // Australia
        510 => Some([b'I', b'D']), // Indonesia (Republic of)
        515 => Some([b'P', b'H']), // Philippines (Republic of the)
        520 => Some([b'T', b'H']), // Thailand
        525 => Some([b'S', b'G']), // Singapore (Republic of)
        528 => Some([b'B', b'N']), // Brunei Darussalam
        530 => Some([b'N', b'Z']), // New Zealand
        534 => Some([b'M', b'P']), // Northern Mariana Islands (Commonwealth of the)
        535 => Some([b'G', b'U']), // Guam
        536 => Some([b'N', b'R']), // Nauru (Republic of)
        537 => Some([b'P', b'G']), // Papua New Guinea
        539 => Some([b'T', b'O']), // Tonga (Kingdom of)
        540 => Some([b'S', b'B']), // Solomon Islands
        541 => Some([b'V', b'U']), // Vanuatu (Republic of)
        542 => Some([b'F', b'J']), // Fiji (Republic of)
        543 => Some([b'W', b'F']), // Wallis and Futuna (French Overseas Territory)
        544 => Some([b'A', b'S']), // American Samoa
        545 => Some([b'K', b'I']), // Kiribati (Republic of)
        546 => Some([b'N', b'C']), // New Caledonia (French Overseas Territory)
        547 => Some([b'P', b'F']), // French Polynesia (French Overseas Territory)
        548 => Some([b'C', b'K']), // Cook Islands
        549 => Some([b'W', b'S']), // Samoa (Independent State of)
        550 => Some([b'F', b'M']), // Micronesia (Federated States of)
        602 => Some([b'E', b'G']), // Egypt (Arab Republic of)
        603 => Some([b'D', b'Z']), // Algeria (People’s Democratic Republic of)
        604 => Some([b'M', b'A']), // Morocco (Kingdom of)
        605 => Some([b'T', b'N']), // Tunisia
        606 => Some([b'L', b'Y']), // Libya (Socialist People’s Libyan Arab Jamahiriya)
        607 => Some([b'G', b'M']), // Gambia (Republic of the)
        608 => Some([b'S', b'N']), // Senegal (Republic of)
        609 => Some([b'M', b'R']), // Mauritania (Islamic Republic of)
        610 => Some([b'M', b'L']), // Mali (Republic of)
        611 => Some([b'G', b'N']), // Guinea (Republic of)
        612 => Some([b'C', b'I']), // Côte d’Ivoire (Republic of)
        613 => Some([b'B', b'F']), // Burkina Faso
        614 => Some([b'N', b'E']), // Niger (Republic of the)
        615 => Some([b'T', b'G']), // Togolese Republic
        616 => Some([b'B', b'J']), // Benin (Republic of)
        617 => Some([b'M', b'U']), // Mauritius (Republic of)
        618 => Some([b'L', b'R']), // Liberia (Republic of)
        619 => Some([b'S', b'L']), // Sierra Leone
        620 => Some([b'G', b'H']), // Ghana
        621 => Some([b'N', b'G']), // Nigeria (Federal Republic of)
        622 => Some([b'T', b'D']), // Chad (Republic of)
        623 => Some([b'C', b'F']), // Central African Republic
        624 => Some([b'C', b'M']), // Cameroon (Republic of)
        625 => Some([b'C', b'V']), // Cape Verde (Republic of)
        626 => Some([b'S', b'T']), // Sao Tome and Principe (Democratic Republic of)
        627 => Some([b'G', b'Q']), // Equatorial Guinea (Republic of)
        628 => Some([b'G', b'A']), // Gabonese Republic
        629 => Some([b'C', b'G']), // Congo (Republic of the)
        630 => Some([b'C', b'D']), // Democratic Republic of the Congo
        631 => Some([b'A', b'O']), // Angola (Republic of)
        632 => Some([b'G', b'W']), // Guinea-Bissau (Republic of)
        633 => Some([b'S', b'C']), // Seychelles (Republic of)
        634 => Some([b'S', b'D']), // Sudan (Republic of the)
        635 => Some([b'R', b'W']), // Rwandese Republic
        636 => Some([b'E', b'T']), // Ethiopia (Federal Democratic Republic of)
        637 => Some([b'S', b'O']), // Somali Democratic Republic
        638 => Some([b'D', b'J']), // Djibouti (Republic of)
        639 => Some([b'K', b'E']), // Kenya (Republic of)
        640 => Some([b'T', b'Z']), // Tanzania (United Republic of)
        641 => Some([b'U', b'G']), // Uganda (Republic of)
        642 => Some([b'B', b'I']), // Burundi (Republic of)
        643 => Some([b'M', b'Z']), // Mozambique (Republic of)
        645 => Some([b'Z', b'M']), // Zambia (Republic of)
        646 => Some([b'M', b'G']), // Madagascar (Republic of)
        647 => Some([b'R', b'E']), // Reunion (French Department of)
        648 => Some([b'Z', b'W']), // Zimbabwe (Republic of)
        649 => Some([b'N', b'A']), // Namibia (Republic of)
        650 => Some([b'M', b'W']), // Malawi
        651 => Some([b'L', b'S']), // Lesotho (Kingdom of)
        652 => Some([b'B', b'W']), // Botswana (Republic of)
        653 => Some([b'S', b'Z']), // Swaziland (Kingdom of)
        654 => Some([b'K', b'M']), // Comoros (Islamic Federal Republic of the)
        655 => Some([b'Z', b'A']), // South Africa (Republic of)
        658 => Some([b'E', b'R']), // Eritrea
        702 => Some([b'B', b'Z']), // Belize
        704 => Some([b'G', b'T']), // Guatemala (Republic of)
        706 => Some([b'S', b'V']), // El Salvador (Republic of)
        708 => Some([b'H', b'N']), // Honduras (Republic of)
        710 => Some([b'N', b'I']), // Nicaragua
        712 => Some([b'C', b'R']), // Costa Rica
        714 => Some([b'P', b'A']), // Panama (Republic of)
        716 => Some([b'P', b'E']), // Peru
        722 => Some([b'A', b'R']), // Argentine Republic
        724 => Some([b'B', b'R']), // Brazil (Federative Republic of)
        725 => Some([b'B', b'R']), // Brazil (Federative Republic of)
        730 => Some([b'C', b'L']), // Chile
        732 => Some([b'C', b'O']), // Colombia (Republic of)
        734 => Some([b'V', b'E']), // Venezuela (Bolivarian Republic of)
        736 => Some([b'B', b'O']), // Bolivia (Republic of)
        738 => Some([b'G', b'Y']), // Guyana
        740 => Some([b'E', b'C']), // Ecuador
        742 => Some([b'G', b'F']), // Guiana (French Department of)
        744 => Some([b'P', b'Y']), // Paraguay (Republic of)
        746 => Some([b'S', b'R']), // Suriname (Republic of)
        748 => Some([b'U', b'Y']), // Uruguay (Eastern Republic of)
        _ => None,
    }
}
