[workspace]

members = [
    "asn1",
    "x690",
    "ldap",
    "x500",
    "idm",
    "rose-transport",
    "x500-client",
    "mock-tcpstream",
    "tsp",
    "cms",
    "tsp-server",
]
