[package]
name = "x691"
version = "0.1.0"
edition = "2021"
authors = [
    "Jonathan M. Wilbur <jonathan@wilbur.space>",
    "Wildboar Software <jonathan.wilbur@wildboarsoftware.com>",
]
description = "Packed Encoding Rules (PER)"
readme = "README.md"
repository = "https://github.com/JonathanWilbur/asn1.rs/tree/master/x691"
license = "MIT"
keywords = ["x690", "asn1", "per", "packed", "encoding"]
categories = ["encoding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wildboar-asn1 = { path = "../asn1" }
x690 = { path = "../x690" }
bitvec = "1.0"
syn = { version = "1.0" }
proc-macro2 = { version = "1.0" }
log = { version = "0.4", features = ["release_max_level_info"] }
