[package]
name = "cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x500 = { path = "../x500" }
asn1 = { path = "../asn1" }
x690 = { path = "../x690" }
